source 'https://rubygems.org'

gem 'jekyll', '~> 3.3.1'
gem 'jekyll-assets', '~> 2.2.8'
gem 'pygments.rb',   '~> 0.6.3'
gem 'sass',     '~> 3.2.8'
gem 'bourbon',  '~> 3.1.6'
gem 'uglifier', '~> 2.5.3'
gem 'static_deploy', '0.2.0'
gem 'rake'
